### ISSUE TITLE
Ajout de contenu en pied de page

### ISSUE THREAD

**Issue by g-forgues** [SerreETS/serreets.github.io#6]
Location: Titre de l'ecole, local?
Ailleurs sur le web: facebook, Etsmtl.ca/clubs, git
Credits -> Remplacer par Membres exec?

**Comment by ldionmarcil** [comment]
Location ferait en effet plus de sens avec le nom de l'école…

Perso je flusherais totallement « Ailleurs sur le web » pour y mettre qqchose d'autre. Reste à voir quoi!

J'étais pas trop certain quoi mettre dans le boute de Credits. En même temps, je pense pas qu'avoir la liste de l'exec là c'est super efficace; y a quand même plusieurs membre et la liste exhaustive est assez longue. Ptete je la metterais dans une nouvelle catégorie « Exec » direct sur la page?

**Comment by ldionmarcil** [comment]
Fix partiel par PR #8, reste à voir pour la partie « Credits »

**Comment by TyMarc** [comment]
Bin, le crédit est bon non? Le crédit revient à Freelancer pour avoir eu le
template

2015-02-24 12:06 GMT-05:00 Louis Dion-Marcil notifications@github.com:

**Comment by g-forgues** [comment]
Ouais ma ça concerne pas trop le club/website. Je le mettrais en petit plus bas avec le copyright.

**Comment by g-forgues** [comment]
Ah j'avais pas vu le premier comment de Louis. On pourrait simplement mettre le logo de l’école a place de Credits? 

http://etsmtl.ca/A-propos/ETS-en-bref/Signature-officielle

**Comment by ldionmarcil** [comment]
@TyMarc Oui le crédit est « bon » mais pas nécessaire. Le projet parent que j'ai forké n'a même pas de licence, donc je me sens pas mal pentoute de pas spécifier la source. De plus, le code source de notre site est ouvert et on voit clairement que c'est un fork, alors double je-m'en-fou.

@g-forgues Le logo de l'école c'est pas une mauvais idée. Ça risque à devenir un spot à commanditaire cet espace-là. Voir site de la DCI:
![2015-02-27-042436_1350x191_scrot](https://cloud.githubusercontent.com/assets/1320868/6410008/91ed88ac-be38-11e4-93b5-6f72d5e1fcd4.png)

Feel free to PR!

**Comment by ldionmarcil** [comment]
Bump @g-forgues ?
